# Generated by Django 3.1.2 on 2020-10-17 18:01

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.CharField(default=blog.models.random_string, max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='daste',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(help_text=False, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=11),
        ),
    ]
