# Generated by Django 3.1.2 on 2020-10-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_vrf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vrf',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
